# Generated by Django 5.1.7 on 2025-03-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='caterogry',
            field=models.CharField(choices=[('player', 'player'), ('Full_court', 'Full_court')], max_length=50),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='location',
            field=models.CharField(choices=[('OSC', 'old sports complex'), ('NSC', 'new sports complex')], max_length=100),
        ),
    ]
