# Generated by Django 5.1.7 on 2025-03-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_infrastructure_caterogry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='condition',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='condition',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
