# Generated by Django 4.2.20 on 2025-03-30 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_semister_otherdata_semester_and_more'),
        ('booking', '0003_alter_equipment_condition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='caterogry',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='caterogry',
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='category',
            field=models.CharField(choices=[('Player', 'Player'), ('Full_court', 'Full Court')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.equipment'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.infrastructure'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='location',
            field=models.CharField(choices=[('OSC', 'Old Sports Complex'), ('NSC', 'New Sports Complex')], max_length=100),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
