# Generated by Django 4.2.20 on 2025-03-30 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0004_rename_caterogry_equipment_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='category',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='location',
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Under Maintenance', 'Under Maintenance')], default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.equipment'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.infrastructure'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missed_bookings', models.PositiveIntegerField(default=0)),
                ('penalty_points', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
