# Generated by Django 4.2.20 on 2025-03-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_equipment_availability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='maintenance_status',
            new_name='if_under_maintenance',
        ),
    ]
