# Generated by Django 4.2.20 on 2025-03-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rename_maintenance_status_equipment_if_under_maintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='if_under_maintenance',
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_under_maintenance',
            field=models.CharField(choices=[('Available', 'Available'), ('Under Maintenance', 'Under Maintenance')], default='Available', max_length=20),
        ),
    ]
