# Generated by Django 4.2.20 on 2025-03-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_equipment_if_under_maintenance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='is_under_maintenance',
            new_name='maintenance_status',
        ),
    ]
