# Generated by Django 4.2.20 on 2025-03-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_rename_is_under_maintenance_equipment_maintenance_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Penalty',
        ),
    ]
