# Generated by Django 5.1.7 on 2025-03-29 12:53

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_profile_picture_delete_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to=user.models.user_profile_picture_path),
        ),
    ]
