# Generated by Django 4.2.20 on 2025-03-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='otherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.PositiveSmallIntegerField()),
                ('CGPA', models.DecimalField(decimal_places=2, max_digits=4)),
                ('semister', models.CharField(max_length=3)),
            ],
        ),
    ]
