# Generated by Django 4.2.20 on 2025-03-30 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_alter_otherdata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherdata',
            old_name='semister',
            new_name='semester',
        ),
        migrations.AlterField(
            model_name='otherdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
